# Generated by Django 2.2.28 on 2023-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vferw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vferw',
            name='bddh',
        ),
        migrations.AddField(
            model_name='vferw',
            name='bddh12',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
