# Generated by Django 2.2.28 on 2023-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230719_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsfsf', models.BigIntegerField()),
                ('xvxbxb', models.BigIntegerField()),
                ('bxbx', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='vferw',
            name='bddh12',
            field=models.BigIntegerField(blank=True),
        ),
    ]
