# Generated by Django 2.2.28 on 2023-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230719_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cswd',
            name='bxbx',
        ),
        migrations.AddField(
            model_name='cswd',
            name='bxb',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cswd',
            name='dsfsf89',
            field=models.BigIntegerField(blank=True),
        ),
    ]
